name: stockflow_app
description: "StockFlow Inventory App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Database (Anda tambah ini, pastikan setup Supabase nanti)
  supabase_flutter: ^2.8.3

  # Scanner (Untuk scan barcode)
  mobile_scanner: ^5.2.3

  # Styling & Formatting
  google_fonts: ^6.2.1
  intl: ^0.19.0

  # PENTING: Untuk buka WhatsApp/Call (Missing dalam list anda tadi)
  url_launcher: ^6.3.1

  # Default icons iOS style
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Updated lints untuk Dart 3
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true